# Generated by Django 3.0.8 on 2020-08-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
