# Generated by Django 3.0.8 on 2020-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herstories', '0002_herstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herstory',
            name='story',
            field=models.CharField(max_length=500),
        ),
    ]
