# Generated by Django 3.0.8 on 2020-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herstories', '0003_auto_20200816_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herstory',
            options={'verbose_name_plural': 'Herstories'},
        ),
        migrations.AddField(
            model_name='herstory',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
