# Generated by Django 3.0.8 on 2020-08-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Run',
            new_name='Event',
        ),
    ]
