# Generated by Django 3.0.8 on 2020-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('distance', models.IntegerField()),
                ('description', models.TextField(default='some string')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
